package logging

const (
	EventApplicationConfigurationInvalid = "application_configuration_invalid"
	EventServerStarting                  = "server_starting"
	EventServerFailed                    = "server_failed"
	EventDatabaseConnected               = "database_connected"
	EventDatabaseConnectionFailed        = "database_connection_failed"
	EventDatabaseHealthCheckFailed       = "database_health_check_failed"
	EventHTTPRouteCompleted              = "http_request_completed"
	EventUserRegistrationCompleted       = "user_registration_completed"
	EventUserRegistrationRejected        = "user_registration_rejected"
	EventUserLoginCompleted              = "user_login_completed"
	EventUserLoginRejected               = "user_login_rejected"
	EventProductCatalogListed            = "product_catalog_listed"
	EventProductCreated                  = "product_created"
	EventProductCreationRejected         = "product_creation_rejected"
	EventAdminMetricsRequested           = "admin_metrics_requested"
	EventAdminAccessRejected             = "admin_access_rejected"
	EventStockReserved                   = "stock_reserved"
	EventOrderCreated                    = "order_created"
	EventAdminOrderCancellationFailed    = "admin_order_cancellation_failed"
	EventAdminOrderCancellationCompleted = "admin_order_cancellation_completed"
	EventCheckoutRejected                = "checkout_rejected"
	EventCheckoutStarted                 = "checkout_started"
	EventCheckoutPreferenceReused        = "checkout_preference_reused"
	EventCheckoutPreferenceCreated       = "checkout_preference_created"
	EventCheckoutAuditFailed             = "checkout_audit_failed"
	EventPaymentWebhookReceived          = "payment_webhook_received"
	EventPaymentWebhookIgnoredPaid       = "payment_webhook_ignored_paid"
	EventPaymentWebhookRecorded          = "payment_webhook_recorded"
	EventPaymentWebhookIgnoredTransition = "payment_webhook_ignored_invalid_transition"
	EventPaymentWebhookAmountRejected    = "payment_webhook_amount_rejected"
	EventPaymentWebhookStockFailed       = "payment_webhook_stock_recovery_failed"
	EventPaymentWebhookApplied           = "payment_webhook_applied"
	EventExpiredOrderReleaseFailed       = "expired_order_release_failed"
	EventExpiredOrderReleaseCompleted    = "expired_order_release_completed"
)
